# Generated by Django 2.2.5 on 2019-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20191024_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.RemoveField(
            model_name='forumcategory',
            name='forums',
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='forums',
            field=models.ManyToManyField(blank=True, null=True, to='forum.Forum'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
