# Generated by Django 2.2.6 on 2019-10-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20191024_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='forum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Forum'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='forums',
            field=models.ManyToManyField(blank=True, to='forum.Forum'),
        ),
    ]
