# Generated by Django 2.2.6 on 2019-10-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20191024_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.Post')),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.Post')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.Post')),
            ],
            bases=('forum.post',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forum.Post')),
                ('main_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.Post')),
            ],
            bases=('forum.post',),
        ),
    ]
