# Generated by Django 2.2.6 on 2019-10-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_reply_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='test',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to_older_reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='forum.Reply'),
        ),
    ]
