# Generated by Django 2.2.6 on 2019-11-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20191029_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pinned_message',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='pinned_message',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='thread_posts',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='pinned_message',
        ),
        migrations.AddField(
            model_name='comment',
            name='thread_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.MainTopic'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('announcement', 'announcement'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='maintopic',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('announcement', 'announcement'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='reply',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('announcement', 'announcement'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
    ]
