# Generated by Django 2.2.6 on 2019-11-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20191101_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='maintopic',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
        migrations.AlterField(
            model_name='reply',
            name='announcement',
            field=models.CharField(choices=[('normal', 'normal'), ('pinned', 'pinned')], default='normal', max_length=12),
        ),
    ]
