# Generated by Django 2.2.6 on 2019-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20191106_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintopic',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
