# Generated by Django 2.2.6 on 2019-11-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(default='', max_length=100),
        ),
    ]
