# Generated by Django 2.2.5 on 2019-10-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts_counter',
            field=models.IntegerField(default=0),
        ),
    ]
