# Generated by Django 2.2.6 on 2019-10-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintopic',
            name='comments',
        ),
        migrations.AddField(
            model_name='maintopic',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='_maintopic_comments_+', to='forum.Comment'),
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='replies',
        ),
        migrations.AddField(
            model_name='maintopic',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='_maintopic_replies_+', to='forum.Reply'),
        ),
    ]
