# Generated by Django 2.2.6 on 2019-10-28 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20191025_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlike',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='like',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='replies',
        ),
        migrations.RemoveField(
            model_name='maintopic',
            name='unlike',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='like',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='unlike',
        ),
        migrations.AddField(
            model_name='comment',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='pinned_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintopic',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintopic',
            name='pinned_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintopic',
            name='thread_posts',
            field=models.ManyToManyField(blank=True, related_name='_maintopic_thread_posts_+', to='forum.Comment'),
        ),
        migrations.AddField(
            model_name='reply',
            name='announcement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='pinned_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.Comment'),
        ),
    ]
